### ISSUE TITLE
allow negative numbers

### ISSUE THREAD

**Issue by matthiaskrgr** [LeopoldArkham/humansize#11]
I understand that it does not make sense to have a file with negative size, however I would like to do something like
````rust
let filesize_old = get_size(file);
do_something_with(file);
let filesize_new = get_size(file);
println!("size difference: {}",  (filesize_new - filesize_old).file_size(options::DECIMAL).unwrap());
````
which will crash if the difference is negative and I had to use some ugly hacks to get around that.
Would be great if would not panic on negative numbers.

https://github.com/LeopoldArkham/humansize/blob/master/src/lib.rs#L224

**Comment by LeopoldArkham** [comment]
Hmm. I understand the use case, but at the same time I feel like it would hide a logic error in most cases.
I could always make allowing negative numbers a configurable option, although that would be a breaking change in theory.

Gonna get back to you in a couple of days, too busy right now to do anything about it anyways!

**Comment by matthiaskrgr** [comment]
Thanks!
For the record this is my current workaround:
````rust
    let size_before = size_before as i64;
    let size_after = size_after as i64;
    let size_diff: i64 = size_after - size_before;

    let sign = if size_diff < 0 { "-" } else { "+" };

    let size_after_human_readable = size_after.file_size(options::DECIMAL).unwrap();
    let size_diff_human_readable = size_diff.abs().file_size(options::DECIMAL).unwrap();
    let size_before_human_readabel = size_before.file_size(options::DECIMAL).unwrap();
````

**Comment by LeopoldArkham** [comment]
So the use case is definitely valid, but an exception IMO, so I'll make it an overridable default:

```

**Comment by LeopoldArkham** [comment]
Ok, @matthiaskrgr, you can update humansize to `1.1.0` and use the code from my previous post to get negative numbers working!

**Comment by matthiaskrgr** [comment]
Works fine here, thanks a lot!
