### ISSUE TITLE
no_std support

### ISSUE THREAD

**Issue by remexre** [LeopoldArkham/humansize#13]
It'd be nice to have support for using `core`+`alloc` only, rather than full-blown `std`.

Although if possible, it'd honestly be nicer to not require `alloc` (for `String`s) and instead return a `Result<FileSizeWrite, FileSizeError>` from `file_size`, where `FileSizeWrite: core::fmt::Write` and `FileSizeError` is similarly non-allocating.

**Comment by LeopoldArkham** [comment]
I'll look into this for the upcoming next release

**Comment by Darksonn** [comment]
The correct trait here is `FileSizeWrite: Display` as opposed to `Write`.
