### ISSUE TITLE
Consider using lowercase 'K' in 'KB'

### ISSUE THREAD

**Issue by ghost** [LeopoldArkham/humansize#15]
(for the decimal variant)
It is used in the SI in lower case.

**Comment by LeopoldArkham** [comment]
Most places I've looked (I think all) use a capital K but the SI prefix is indeed supposed to be lowercase.
I won't change the established convention by default, but I might add an option flag to use a lowercase prefix in the next release.

Thanks for the input

**Comment by LeopoldArkham** [comment]
Previous comment was miguided, next version will use the corrected SI style
