### ISSUE TITLE
Even more configurable!

### ISSUE THREAD

**Issue by LeopoldArkham** [LeopoldArkham/humansize#2]
#Reminder to add the following customization options:

- [x] Space/No space before the units: `55 MB` / `55MB`
- [x] Ability to add a suffix to the units. E.g. if I specify the `/s` string, I get `55 MB/s`
- [x] Ability to represent the number as `KB`, `MB`, etc, regardless of its size. E.g. if I specify `KB`, `55 MB` would come out as `55 000 KB`.

All done via the options struct, with sensible values for the defaults

**Comment by sakrma07** [comment]
Allright, I have a little bit of time to try working on this now. So it's like we want to give people a warning if they don't specify those options?

**Comment by sakrma07** [comment]
Allright, I have some time to try working on this. Mind you, I am new to github, so if I do something wrong please tell me.

**Comment by LeopoldArkham** [comment]
Sounds good, glad to have you!
Let me know here if you have any questions on the code or the language, I don't mind long discussions on GH issues

**Comment by LeopoldArkham** [comment]
One down.

**Comment by LeopoldArkham** [comment]
Two down!

**Comment by LeopoldArkham** [comment]
And done.
