### ISSUE TITLE
Exclude feature tests when uploading to crates.io

### ISSUE THREAD

**Issue by figsoda** [LeopoldArkham/humansize#24]
When updating genact in nixpkgs (https://github.com/NixOS/nixpkgs/pull/191077), I ran into a hash mismatch for the cargo vendor because the `feature-tests` directory is absent on macos for some reason. I still don't know what is causing this issue, but It would be nice if the directory could be [excluded in Cargo.toml](https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields).

**Comment by LeopoldArkham** [comment]
Thanks for the report, this is done in the new version.
