### ISSUE TITLE
#[derive(Default)] requires Rust 1.62.0

### ISSUE THREAD

**Issue by link2xt** [LeopoldArkham/humansize#25]
This feature was stabilized only recently: https://blog.rust-lang.org/2022/06/30/Rust-1.62.0.html#default-enum-variants

Because it is used in `humansize` version 2 here, new version cannot be used with Rust 1.61.0 and earlier:
https://github.com/LeopoldArkham/humansize/blob/8b6903f3e34cd8bfb058d42f6510b880b70fbd9d/src/options/mod.rs#L11

Is there an MSRV policy for humansize?

**Comment by LeopoldArkham** [comment]
Thank you for the report and the PR, I have merged your contribution in version `2.1.2`
