### ISSUE TITLE
Make it faster

### ISSUE THREAD

**Issue by LeopoldArkham** [LeopoldArkham/humansize#4]
Currently the code uses a loop that divides the size by `1K` until size becomes less than `1k` to detrmine the suffix.

_Perhaps_ this _could_ be re-written to use [count_zeros](https://doc.rust-lang.org/std/primitive.u32.html#method.count_zeros) for performance.

This needs to be profiled though, to avoid a naive mis-optimization.

**Comment by mwilli20** [comment]
I could be wrong, but looking at your code, it could be 1024 or 1000 so you can't use a simple count_zeros, trailing_zeros, or size check. So you could right the code specialized for one size over the other or you could if you wanted to treat divider as if it was 1000 to use the other "optimizations". But this too wouldn't be great as you'd still need a branch to see if you guessed right as. 

What you are really looking for mathematically is a (size.ln()  / divider.ln()).floor() . This would tell you exactly how many times you would want to divide. However this is probably more expensive than the while loop itself. I wouldn't be sure without testing it.

Just my two cents.

**Comment by mwilli20** [comment]
This is a playground link just showing off what I was talking about with the math. https://is.gd/65Zjaa . Once again though this would have to be bench marked to see if it actually makes sense. We are talking possible branch prediction misses on the while loop vs obviously more calculations with two ln and a pow call.

**Comment by LeopoldArkham** [comment]
Good catch! Only had 1024 in mind when I made a note of this. IIRC it's implementation dependent how `ln(x)` will be calculated, but this would almost certainly be a misoptimization. I may revisit this someday, but I'll close for now.

Cheers!

**Comment by mwilli20** [comment]
My pleasure, enjoy the weekend.
